version: "3"

services:
  master:
    image: redis:5.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "redis_master"
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTHOST=127.0.0.1
      - CLIENTPORT=6379
      - MASTERHOST=
      - MASTERPORT=
    restart: always

  slave1:
    image: redis:5.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "redis_slave_1"
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTHOST=127.0.0.1
      - CLIENTPORT=6380
      - MASTERHOST=127.0.0.1
      - MASTERPORT=6379
    restart: always

  slave2:
    image: redis:5.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "redis_slave_2"
    network_mode: "host"
    environment:
      - REQUIREPASS=password1234
      - CLIENTHOST=127.0.0.1
      - CLIENTPORT=6381
      - MASTERHOST=127.0.0.1
      - MASTERPORT=6379
    restart: always
