version: '3'

services:
  event-api:
    image: event-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-api
    command: npm run start
    volumes:
      - ./dist:/home/node/api/dist
      - ./src:/home/node/api/src
      - ./package.json:/home/node/api/package.json
      - ./.env:/home/node/api/.env
      - ./.env.example:/home/node/api/.env.example
      - ./.eslintrc:/home/node/api/.eslintrc
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: development
      PORT: 9000
      TZ: Asia/Seoul
    tty: true
